export const database = [
    {
        nombre: "Fibra Optica 300MB",
        descripcion: "Internet 300MB + Telefonia Fija",
        precio: 1700,
        color: "#f2d886",
        id: 1,
    },
    {
        nombre: "Fibra Optica 500MB",
        descripcion: "Internet 500MB + Telefonia Fija",
        precio: 2400,
        color: "#7dffff",
        id: 2,
    },
    {
        nombre: "Fibra Optica 1000MB",
        descripcion: "Internet 1000MB + Telefonia Fija",
        precio: 3600,
        color: "#3fde90",
        id: 3,
    },
    {
        nombre: "Fibra Optica 300MB + TV HD",
        descripcion: "Internet 300MB + Telefonia Fija + TV HD 31 canales",
        precio: 2650,
        color: "#ffd5f5",
        id: 4,
    },
    {
        nombre: "Fibra Optica 500MB + TV HD",
        descripcion: "Internet 500MB + Telefonia Fija + TV HD 31 canales",
        precio: 3350,
        color: "#7a6bfd",
        id: 5,
    },
    {
        nombre: "Fibra Optica 1000MB + TV HD",
        descripcion: "Internet 1000MB + Telefonia Fija + TV HD 31 canales",
        precio: 4550,
        color: "#ffcd5a",
        id: 6,
    },
    {
        nombre: "Fibra Optica 300MB + TV HD",
        descripcion: "Internet 300MB + Telefonia Fija + TV HD 93 canales",
        precio: 4050,
        color: "#04f265",
        id: 7,
    },
    {
        nombre: "Fibra Optica 500MB + TV HD",
        descripcion: "Internet 500MB + Telefonia Fija + TV HD 93 canales",
        precio: 4750,
        color: "#dee9f6",
        id: 8,
    },
    {
        nombre: "Fibra Optica 1000MB + TV HD",
        descripcion: "Internet 1000MB + Telefonia Fija + TV HD 93 canales",
        precio: 5950,
        color: "#8b88f5",
        id: 9,
    },
]